name: Build Android APK
on: [push]

jobs:
    build-apk:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out
              uses: actions/checkout@v3
            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
                
            - name: Build with Gradle
              run: ./gradlew assembleDebug
              
            - name: Upload APK
              uses: actions/upload-artifact@v3
              with:
                name: APK
                path: app/build/outputs/apk/debug/app-debug.apk
    